[workspace]
resolver = "2"
members = [
    "cli",
    "crates/decoder",
    "crates/evaluator",
    "crates/event-watcher",
    "crates/fetcher",
    "crates/common",
]

[workspace.dependencies]
common = { version = "0.1.0", path = "crates/common" }
decoder = { version = "0.1.0", path = "crates/decoder" }
fetcher = { version = "0.1.0", path = "crates/fetcher" }
evaluator = { version = "0.1.0", path = "crates/evaluator" }
tokio = { version = "1", features = ["full"] }
alloy-dyn-abi = "0.6.2"
alloy-primitives = "0.6.2"
alloy-rlp = { version = "0.3.4", features = ["derive"] }
anyhow = "1.0.79"
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", rev = "01d3df3" }
num-bigint = "0.4.0"
num-traits = "0.2.14"
