[workspace]
resolver = "2"
members = [
    "cli",
    "crates/decoder",
    "crates/evaluator",
    "crates/event-watcher",
    "crates/fetcher",
    "crates/tasks-compiler",
    "crates/types",
]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
alloy-dyn-abi = "0.6.2"
alloy-primitives = "0.6.2"
anyhow = "1.0.79"
