[workspace]
resolver = "2"
members = ["cli", "crates/evaluator", "crates/common"]

[workspace.dependencies]
common = { version = "0.1.0", path = "crates/common" }
evaluator = { version = "0.1.0", path = "crates/evaluator" }
tokio = { version = "1", features = ["full"] }
alloy-dyn-abi = "0.6.2"
alloy-primitives = "0.6.2"
alloy-merkle-tree = { version = "0.5.0" }
alloy-rlp = { version = "0.3.4", features = ["derive"] }
anyhow = "1.0.79"
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", rev = "01d3df3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
