version: '3.8'

services:
  runner:
    build:
      context: .
      dockerfile: ./runner.dockerfile
    env_file:
      - .env
    volumes:
      - ./input.json:/hdp-runner/input.json
      - ./output.json:/hdp-runner/output.json
      - ./cairo.pie:/hdp-runner/cairo.pie
    restart: always