# TOML configuration file to build hdp 
# All options are commented out by default in this file, and they're commented
# out with their default values


# dry-run-cairo-path = "build/contract_dry_run.json"

# =============================================================================
# provider option
# =============================================================================

[[chains]]
chain-id = 1
rpc-url = "https://ethereum-rpc.publicnode.com"
# rpc-chunk-size = 100

[[chains]]
chain-id = 11155111
rpc-url = "https://ethereum-sepolia-rpc.publicnode.com"
# rpc-chunk-size = 100


# =============================================================================
# output file option
# =============================================================================

# pre-processor-output-file = "preprocess_output.json"


# if you add this option, fetch keys file will be saved in target path
# save-fetch-keys-file = "dry_run_output.json"
