[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]
description = "Run rustfmt to check the code formatting without making changes."

[tasks.clean]
command = "cargo"
args = ["clean"]
description = "Clean up the project by removing the target directory."

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-Dwarnings"]
description = "Run clippy to catch common mistakes and improve your Rust code."

[tasks.test]
workspace = false
command = "cargo"
args = ["llvm-cov", "nextest"]
description = "Execute all unit tests in the workspace."

[tasks.run-ci-flow]
workspace = false
description = "Run the entire CI pipeline including format, clippy, and test checks."
dependencies = ["format", "clippy", "test"]
