[package]
name = "decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-dyn-abi = { workspace = true }
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
types = { workspace = true }
datalake = { workspace = true }
