use crate::module::Module;

/*
    input.json file that will be passed to the processor, is generated by this struct.

*/

pub struct ProcessorInput {
    /// Detail sierra code of the module.
    /// This will be loaded to bootloader.
    // TODO: potentially we can merge multiple modules into one file
    module_bytes: Vec<u8>,
    modules: Vec<Module>,
    /// Fetched proofs per each fetch point.
    proofs: Vec<String>,
}

impl ProcessorInput {
    pub fn new(module_bytes: Vec<u8>, modules: Vec<Module>, proofs: Vec<String>) -> Self {
        Self {
            module_bytes,
            modules,
            proofs,
        }
    }

    pub fn to_bytes(&self) -> Vec<u8> {
        todo!("Convert ProcessorInput to json")
    }
}
