[package]
name = "hdp-cli"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
description = "Interact Herodotus Data Processor via CLI"
authors = ["Pia <pia@herodotus.dev>"]
homepage = "https://herodotus.dev/"
repository = "https://github.com/HerodotusDev/hdp"
readme = "../README.md"
keywords = ["blockchain", "ethereum", "rust", "data-processor", "storage-proof"]
categories = [
    "command-line-interface",
    "cryptography::cryptocurrencies",
    "compilers",
    "asynchronous",
]

[[bin]]
name = "hdp"
path = "src/main.rs"

[dependencies]
hdp-core = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
hdp-provider = { workspace = true }
hdp-primitives = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4.4.4", features = ["derive"] }
dotenv = "0.15.0"
tracing-subscriber = "0.3.0"
inquire = "0.7.4"
alloy = { workspace = true }
