[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decoder = { workspace = true }
common = { workspace = true }
evaluator = { workspace = true }
anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true

clap = { version = "4.4.4", features = ["derive"] }
dotenv = "0.15.0"


[[bin]]
name = "hdp"
path = "src/main.rs"
