use crate::module::Module;

/*

    input.json file that will be passed to the preprocessor, is generated by this struct.
*/

pub struct PreProcessorInput {
    module: Module,
    /// Detail sierra code of the module.
    /// This will be loaded to bootloader.
    module_bytes: Vec<u8>,
}

impl PreProcessorInput {
    pub fn new(module: Module, module_bytes: Vec<u8>) -> Self {
        Self {
            module,
            module_bytes,
        }
    }

    /// Turn into bytes type so to write to file.
    pub fn to_bytes(&self) -> Vec<u8> {
        todo!("Convert PreProcessorInput to json")
    }

    pub fn get_module_bytes(&self) -> Vec<u8> {
        self.module_bytes.clone()
    }

    pub fn get_module(&self) -> Module {
        self.module.clone()
    }
}
