[package]
name = "types"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-dyn-abi = { workspace = true }
alloy-primitives = { workspace = true }
common = { workspace = true }
anyhow = { workspace = true }
fetcher = { workspace = true }
num-bigint = "0.4.0"
num-traits = "0.2.14"
