name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROVIDER_URL_ETHEREUM_SEPOLIA: ${{ secrets.PROVIDER_URL_ETHEREUM_SEPOLIA }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - name: Install cargo-make
        run: cargo install --debug cargo-make
      - name: Run clippy and formatter checks
        run: cargo make run-ci-flow
