name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - name: Run clippy and formatter checks
        run: |
          cargo clippy --all --all-targets -- -D warnings
          cargo fmt -- --check
      - name: Run Rust tests
        run: cargo test --all --all-targets -- --nocapture
      - name: Install cargo-make
        run: cargo install --debug cargo-make
      - name: Run CI flow
        run: cargo make run-full-flow
